# Load the data

In [2]:
import pandas as pd
df = pd.read_json('data/eval_other_models/Re__Github_repo/wdcproducts80cc20rnd000un_validset_with_predictions.json.gz', compression='gzip', lines=True)

In [3]:
# export df to csv
df.to_csv('data/wdcproducts80cc20rnd000un_valid_small_with_predictions.csv')

In [3]:
df

,id_left,brand_left,title_left,description_left,price_left,priceCurrency_left,specTableContent_left,cluster_id_left,id_right,brand_right,...,priceCurrency_right,specTableContent_right,cluster_id_right,pair_id,label,is_hard_negative,roberta-base_logits,roberta-base_prediction,rsupcon-base_logits,rsupcon-base_prediction
0,36911227,None,Corsair Carbide 275R Tempered Glass Blanca,None,89.9,EUR,NaN,717069,95352771,Logitech,...,GBP,NaN,301204,36911227#95352771,0,False,"[3.8274521828, -4.2882475853]",0,[0.0],0
1,9216392,Shimano,XT M8000 11-Speed Cassette 11-40T,##Shimano XT M8000 11-Speed Cassette 11-40TFor...,79,GBP,NaN,328225,12748766,None,...,HKD,NaN,3739198,9216392#12748766,0,True,"[3.8432211876, -4.2999682426]",0,[0.0],0
2,86974759,None,0000005990| Sony E 30mm F3.5 Macro Lens,0000005990| Sony E 30mm F3.5 Macro Lens,599.00,AUD,NaN,213496,3970721,None,...,SAR,NaN,740038,86974759#3970721,0,True,"[3.7968792915, -4.2594017982]",0,[0.0],0
3,85527916,None,SanDisk SSD PLUS 480 GB Sata III 2.5 Inch Inte...,DURABLE DESIGN: SanDisk Solid State Drives hav...,7.5E1,GBP,NaN,1037877,62156844,Western Digital,...,USD,NaN,483248,85527916#62156844,0,True,"[3.8346962929, -4.2963290215]",0,[0.0],0
4,32153750,None,"E260, E360, E460 3.5K Return Program Toner Car...",CZ distribuce / 0734646064620 / E260A11E /,3228.00,CZK,NaN,1913870,34520225,Oki,...,GBP,NaN,140469,32153750#34520225,0,True,"[3.8033189774, -4.2682704926]",0,[0.0],0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,31292975,Zebra,Zebra Black Resin Monochrome Ribbon - 1000 Images,Black Resin Monochrome Ribbon - 1000 ImagesMfr...,None,None,NaN,5836450,21556335,None,...,USD,NaN,163499,31292975#21556335,0,True,"[3.5426645279, -3.9851288795]",0,[0.0],0
4496,15417028,None,"Samsung CF390 27"" 4ms HDMI Curved Monitor","Samsung CF390 27"" 4ms HDMI Curved Monitor",175.88,GBP,NaN,709380,29524431,None,...,EUR,NaN,1578824,15417028#29524431,0,False,"[3.8305664062, -4.2897052765]",0,[0.0],0
4497,96595609,Daniel Wellington,Daniel Wellington Classic Sheffield Watch | Si...,Nothing is as sleek and refined as a supple bl...,229.00,USD,NaN,5135259,33918678,DANIEL WELLINGTON,...,EUR,NaN,48610,96595609#33918678,0,True,"[-1.9202262163000001, 1.9179266690999999]",1,[0.0],0
4498,23598269,None,HyperX Predator XMP 16GB [2x8GB 3333MHz DDR4 C...,None,379,PLN,NaN,499316,16693470,None,...,PLN,NaN,1249448,23598269#16693470,0,True,"[3.7833967209, -4.2472724915]",0,[0.0],0
4499,35690339,None,Sony 24-240mm f/3.5-6.3 Zoom Lens,This Sonyzoomlens is perfect for all of the ob...,1298,AUD,NaN,740038,45511817,None,...,AUD,NaN,21809,35690339#45511817,0,True,"[3.8080546856, -4.2721176147]",0,[0.0],0

In [ ]:
# random sample of 100 rows and save to csv
df.sample(n=100).to_csv('data/test/random_sample_100.csv')

In [5]:
# sample 200 rows and save to csv
df.sample(n=200).to_csv('data/test/random_sample_200.csv')

In [4]:
# filter to cluster_id_left == 1406172
df[df['cluster_id_left'] == 1406172]

,id_left,brand_left,title_left,description_left,price_left,priceCurrency_left,specTableContent_left,cluster_id_left,id_right,brand_right,...,priceCurrency_right,specTableContent_right,cluster_id_right,pair_id,label,is_hard_negative,roberta-base_logits,roberta-base_prediction,rsupcon-base_logits,rsupcon-base_prediction
179,30515563,None,Garmin Fenix 5S Black Sapphire with Black Band,None,4.77E2,EUR,NaN,1406172,82659340,None,...,AUD,NaN,1406172,30515563#82659340,1,False,"[-4.3920264244, 4.6851463318]",1,[1.0],1
334,82659340,None,Garmin Black fenix 5S Sapphire Watch with Blac...,Get More From Your Workout with Less on Your W...,949.0,AUD,NaN,1406172,22883953,Garmin,...,AUD,NaN,139209,82659340#22883953,0,True,"[3.7170090675000003, -4.1857123375]",0,[0.0],0
1102,82659340,None,Garmin Black fenix 5S Sapphire Watch with Blac...,Get More From Your Workout with Less on Your W...,949.0,AUD,NaN,1406172,89309643,Garmin,...,RON,NaN,1138411,82659340#89309643,0,True,"[3.7965111732, -4.2600083351]",0,[0.0],0
1469,82659340,None,Garmin Black fenix 5S Sapphire Watch with Blac...,Get More From Your Workout with Less on Your W...,949.0,AUD,NaN,1406172,75263315,None,...,CZK,NaN,1138411,82659340#75263315,0,True,"[3.7941963673, -4.2584056854]",0,[0.0],0
1606,30515563,None,Garmin Fenix 5S Black Sapphire with Black Band,None,4.77E2,EUR,NaN,1406172,84159045,None,...,EUR,NaN,139209,30515563#84159045,0,True,"[3.7840075493, -4.2504501343]",0,[0.0],0
1827,82659340,None,Garmin Black fenix 5S Sapphire Watch with Blac...,Get More From Your Workout with Less on Your W...,949.0,AUD,NaN,1406172,7064344,Garmin,...,EUR,NaN,23040,82659340#7064344,0,True,"[3.581799984, -4.0302586555]",0,[0.0],0
2460,30515563,None,Garmin Fenix 5S Black Sapphire with Black Band,None,4.77E2,EUR,NaN,1406172,16490330,None,...,AUD,NaN,982918,30515563#16490330,0,True,"[3.7997112274, -4.2632703781]",0,[0.0],0
3754,30515563,None,Garmin Fenix 5S Black Sapphire with Black Band,None,4.77E2,EUR,NaN,1406172,89309643,Garmin,...,RON,NaN,1138411,30515563#89309643,0,True,"[3.7793519497, -4.2439222336]",0,[0.0],0
3914,82659340,None,Garmin Black fenix 5S Sapphire Watch with Blac...,Get More From Your Workout with Less on Your W...,949.0,AUD,NaN,1406172,30651444,Garmin,...,GBP,NaN,1761376,82659340#30651444,0,True,"[3.8164668083, -4.2796597481]",0,[0.0],0
4034,30515563,None,Garmin Fenix 5S Black Sapphire with Black Band,None,4.77E2,EUR,NaN,1406172,75263315,None,...,CZK,NaN,1138411,30515563#75263315,0,True,"[3.7732005119, -4.2358636856]",0,[0.0],0

In [5]:
# count the number of times brand_left or brand_right does not equal None
df[(df['brand_left'].notnull()) | (df['brand_right'].notnull())].shape[0]

2570

In [6]:
# Are these the same product?
# product 1: Wireless USB Adapter TP-LINK TL-WN821N 300Mbps, 802.11n/g/b	
# product 2: TP-Link Archer T9UH Wireless USB Adapter, Wireless AC1900
# yes or no?
# yes

In [7]:
# Look at cases where both models ("roberta-base_prediction", "rsupcon-base_prediction") are wrong don't match the label ("label")
df[(df['roberta-base_prediction'] != df['label']) & (df['rsupcon-base_prediction'] != df['label'])]

Empty DataFrame
Columns: [id_left, brand_left, title_left, description_left, price_left, priceCurrency_left, specTableContent_left, cluster_id_left, id_right, brand_right, title_right, description_right, price_right, priceCurrency_right, specTableContent_right, cluster_id_right, pair_id, label, is_hard_negative, roberta-base_logits, roberta-base_prediction, rsupcon-base_logits, rsupcon-base_prediction]
Index: []

[0 rows x 23 columns]

In [8]:
# Look at cases where one model ("roberta-base_prediction", "rsupcon-base_prediction") is wrong don't match the label ("label")
df[(df['roberta-base_prediction'] != df['label']) | (df['rsupcon-base_prediction'] != df['label'])]

,id_left,brand_left,title_left,description_left,price_left,priceCurrency_left,specTableContent_left,cluster_id_left,id_right,brand_right,...,priceCurrency_right,specTableContent_right,cluster_id_right,pair_id,label,is_hard_negative,roberta-base_logits,roberta-base_prediction,rsupcon-base_logits,rsupcon-base_prediction
7,66462363,Audio Technica,Audio Technica ATH-M50x Professional Monitor H...,This is the most critically acclaimed model in...,122.00,GBP,NaN,1889634,91241309,None,...,NZD,NaN,1084160,66462363#91241309,0,True,"[-1.9811097383, 1.9827538729]",1,[0.0],0
14,821722,None,"3M - Privacy filter for desktop 27\""\"" widescr...","3M Privacy filter for desktop 27\""\"" widescree...",1940.00,SEK,NaN,2996705,41263175,None,...,SEK,NaN,2996705,821722#41263175,1,False,"[1.0364459753, -1.1522978544]",0,[1.0],1
21,43410009,None,TISSOT SEASTAR 1000 AUTOMATIC T120.407.11.051.00,DESCRIPTIONThe Tissot Seastar 1000 merges styl...,"2,550.00",MYR,NaN,330408,76613072,None,...,EUR,NaN,330408,43410009#76613072,1,False,"[1.0417864323, -1.1085938215]",0,[1.0],1
27,42324571,None,"3M - Privacy filter 23\"" widescreen","3M Privacy filter 23\"" widescreen (PF230W9F) -...",1849.48,DKK,NaN,654362,32709637,3M,...,USD,NaN,3303908,42324571#32709637,0,True,"[-3.4588589668, 3.627374649]",1,[0.0],0
29,56989328,None,Traveler's Notebook Refill - Grid,Midori grid white paper great for capturing sc...,7.00,AUD,NaN,2662935,83491918,None,...,CAD,NaN,2662935,56989328#83491918,1,False,"[0.5102652907, -0.5963104963]",0,[1.0],1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4398,63687251,None,TP-Link EAP225-Outdoor AC1200 Dual Band Outdoo...,None,6000,PHP,NaN,6665678,78212459,None,...,BRL,NaN,233795,63687251#78212459,0,True,"[-3.6939213276, 3.945920229]",1,[0.0],0
4415,66649332,POKEMON,POKEMON POKEMON SWSH2 REBEL CLASH 3PK BLISTER ...,None,15.99,CAD,NaN,3227349,17589843,None,...,USD,NaN,2490160,66649332#17589843,0,True,"[-4.2311544418, 4.5329031944]",1,[0.0],0
4431,821722,None,"3M - Privacy filter for desktop 27\""\"" widescr...","3M Privacy filter for desktop 27\""\"" widescree...",1940.00,SEK,NaN,2996705,42324571,None,...,DKK,NaN,654362,821722#42324571,0,True,"[-2.9050140381, 3.0086939335]",1,[0.0],0
4476,69155979,None,Crucial 4GB DDR3L / 1600 C11 DIMM (Low volt.),Guaranteed-compatible with the ASUS P8Z68-V LX,2.395E1,EUR,NaN,2395112,63871716,None,...,MUR,NaN,2395112,69155979#63871716,1,False,"[3.5091035366, -3.9778354168]",0,[1.0],1
4497,96595609,Daniel Wellington,Daniel Wellington Classic Sheffield Watch | Si...,Nothing is as sleek and refined as a supple bl...,229.00,USD,NaN,5135259,33918678,DANIEL WELLINGTON,...,EUR,NaN,48610,96595609#33918678,0,True,"[-1.9202262163000001, 1.9179266690999999]",1,[0.0],0

In [9]:
# How often does the label not match the prediction of roberta-base?
df[df['roberta-base_prediction'] != df['label']].shape[0]
df[df['roberta-base_prediction'] != df['label']].to_csv('data/roberta-base_prediction_not_equal_to_label.csv')

In [11]:
# Create a new dataframe with only non matches between roberta-base_prediction and label
df_roberta_base_not_equal_to_label = df[df['roberta-base_prediction'] != df['label']]

In [15]:
# Get number of rows in df_roberta_base_not_equal_to_label
df_roberta_base_not_equal_to_label.shape[0]

220

In [19]:
# Drop all rows where one title is null (i.e. where one title is missing) or with less than 5 characters
df_roberta_base_not_equal_to_label = df_roberta_base_not_equal_to_label.dropna(subset=['title_left', 'title_right'])
df_roberta_base_not_equal_to_label = df_roberta_base_not_equal_to_label[df_roberta_base_not_equal_to_label['title_left'].str.len() > 5]
df_roberta_base_not_equal_to_label.shape[0]

220

In [21]:
# Drop all the rows where the titles are the same
df_roberta_base_not_equal_to_label = df_roberta_base_not_equal_to_label[df_roberta_base_not_equal_to_label['title_left'] != df_roberta_base_not_equal_to_label['title_right']]
df_roberta_base_not_equal_to_label.shape[0]

220

In [22]:
# Randomly sample 100 rows from df_roberta_base_not_equal_to_label
df_roberta_base_not_equal_to_label = df_roberta_base_not_equal_to_label.sample(n=100, random_state=1)
df_roberta_base_not_equal_to_label.shape[0]

100

In [25]:
# Export df_roberta_base_not_equal_to_label to csv and excel
df_roberta_base_not_equal_to_label.to_csv('data/test/testset.csv')
df_roberta_base_not_equal_to_label.to_excel('data/test/testset.xlsx')

Verwendung: java [Optionen] <mainclass> [args...]
           (zur Ausführung einer Klasse)
   oder  java [Optionen] -jar <jarfile> [args...]
           (zur Ausführung einer JAR-Datei)
   oder  java [Optionen] -m <module>[/<mainclass>] [args...]
       java [Optionen] --module <module>[/<mainclass>] [args...]
            (zur Ausführung der Hauptklasse in einem Modul)

 Argumente, die auf die Hauptklasse folgen, -jar <jarfile>, -m oder --module
 <module>/<mainclass> werden als Argumente für die Hauptklasse übergeben.

 wobei "Optionen" Folgendes umfasst:

    -cp <Klassensuchpfad mit Verzeichnissen und ZIP-/JAR-Dateien>
    -classpath <Klassensuchpfad mit Verzeichnissen und ZIP-/JAR-Dateien>
    --class-path <Klassensuchpfad mit Verzeichnissen und ZIP-/JAR-Dateien>
                  Eine durch : getrennte Liste mit Verzeichnissen, JAR-Archiven
                  und ZIP-Archiven, in denen nach Klassendateien gesucht wird.
    -p <Modulpfad>
    --module-path <Modulpfad>...
                  Eine durch : getrennte Liste mit Verzeichnissen, von denen jedes Verzeichnis
                  ein Verzeichnis mit Modulen ist.
    --upgrade-module-path <Modulpfad>...
                  Eine durch : getrennte Liste mit Verzeichnissen, von denen jedes Verzeichnis
                  ein Verzeichnis mit Modulen ist, die upgradefähige
                  Module im Laufzeitimage ersetzen
    --add-modules <Modulname>[,<Modulname>...]
                  Root-Module, die zusätzlich zum anfänglichen Modul aufgelöst werden sollen.
                  <Modulname> kann auch wie folgt lauten: ALL-DEFAULT, ALL-SYSTEM,
                  ALL-MODULE-PATH.
    --list-modules
                  Listet beobachtbare Module auf und beendet den Vorgang
    -d <Modulname>
    --describe-module <Modulname>
                  Beschreibt ein Modul und beendet den Vorgang
    --dry-run     Erstellt eine VM und lädt die Hauptklasse, führt aber nicht die Hauptmethode aus.
                  Die Option "--dry-run" kann nützlich sein, um die
                  Befehlszeilenoptionen, wie die Modulsystemkonfiguration, zu validieren.
    --validate-modules
                  Validiert alle Module und beendet den Vorgang
                  Die Option "--validate-modules" kann nützlich sein, um
                  Konflikte und andere Fehler mit Modulen auf dem Modulpfad zu ermitteln.
    -D<Name>=<Wert>
                  Legt eine Systemeigenschaft fest
    -verbose:[class|module|gc|jni]
                  Ausgabe im Verbose-Modus aktivieren
    -version      Gibt die Produktversion an den Fehlerstream aus und beendet den Vorgang
    --version      Gibt die Produktversion an den Outputstream aus und beendet den Vorgang
    -showversion  Gibt die Produktversion an den Fehlerstream aus und setzt den Vorgang fort
    --show-version
                  Gibt die Produktversion an den Outputstream aus und setzt den Vorgang fort
    --show-module-resolution
                  Zeigt die Modulauflösungsausgabe beim Start an
    -? -h -help
                  Gibt diese Hilfemeldung an den Fehlerstream aus
    --help        Gibt diese Hilfemeldung an den Outputstream aus
    -X            Gibt Hilfe zu zusätzlichen Optionen an den Fehlerstream aus
    --help-extra  Gibt Hilfe zu zusätzlichen Optionen an den Outputstream aus
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  Aktiviert Assertions mit angegebener Granularität
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  Deaktiviert Assertions mit angegebener Granularität
    -esa | -enablesystemassertions
                  Aktiviert System-Assertions
    -dsa | -disablesystemassertions
                  Deaktiviert System-Assertions
    -agentlib:<libname>[=<options>]
                  Lädt die native Agent Library <libname>. Beispiel: -agentlib:jdwp
                  siehe auch -agentlib:jdwp=help
    -agentpath:<pathname>[=<options>]
                  Lädt die native Agent Library mit dem vollständigen Pfadnamen
    -javaagent:<jarpath>[=<options>]
                  Lädt den Java-Programmiersprachen-Agent, siehe java.lang.instrument
    -splash:<imagepath>
                  Zeigt den Startbildschirm mit einem angegebenen Bild an
                  Skalierte HiDPI-Bilder werden automatisch unterstützt und verwendet,
                  falls verfügbar. Der nicht skalierte Bilddateiname (Beispiel: image.ext)
                  muss immer als Argument an die Option "-splash" übergeben werden.
                  Das am besten geeignete angegebene skalierte Bild wird
                  automatisch ausgewählt.
                  Weitere Informationen finden Sie in der Dokumentation zur SplashScreen-API
    @argument files
                  Eine oder mehrere Argumentdateien mit Optionen
    -disable-@files
                  Verhindert die weitere Erweiterung von Argumentdateien
Um ein Argument für eine lange Option anzugeben, können Sie --<Name>=<Wert> oder
--<Name> <Wert> verwenden.

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     |████████████████████████████████| 249 kB 4.0 MB/s eta 0:00:01
Collecting et-xmlfile
  Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2
WARNING: You are using pip version 21.2.4; however, version 23.1.1 is available.
You should consider upgrading via the '/Users/aaronsteiner/Documents/GitHub/fss23seminar/env/bin/python3 -m pip install --upgrade pip' command.

In [10]:
# How often does the label not match the prediction of rsupcon-base?
df[df['rsupcon-base_prediction'] != df['label']]

Empty DataFrame
Columns: [id_left, brand_left, title_left, description_left, price_left, priceCurrency_left, specTableContent_left, cluster_id_left, id_right, brand_right, title_right, description_right, price_right, priceCurrency_right, specTableContent_right, cluster_id_right, pair_id, label, is_hard_negative, roberta-base_logits, roberta-base_prediction, rsupcon-base_logits, rsupcon-base_prediction]
Index: []

[0 rows x 23 columns]

In [8]:
# load csv
df = pd.read_csv('data/test/curated_benchmark.csv', sep=';')

df

,Unnamed: 0,id_left,brand_left,title_left,description_left,price_left,priceCurrency_left,specTableContent_left,cluster_id_left,id_right,...,specTableContent_right,cluster_id_right,pair_id,label,is_hard_negative,roberta-base_logits,roberta-base_prediction,rsupcon-base_logits,rsupcon-base_prediction,Aaron
0,1349,45334125,NaN,Pen Drive SanDisk 64GB Cruzer Glide USB 2.0,NaN,"9,86",EUR,NaN,763994,9787254,...,NaN,279041,45334125#9787254,0,True,"[3.7204918861, -4.1918787956]",0,[0.0],0,1.0
1,1056,7567487,NaN,PEN DRIVE 16GB KINGSTON USB 3.0 DTIG4/16GB,PEN DRIVE 16GB KINGSTON USB 3.0 DTIG4/16GB Dat...,Apr 84,EUR,NaN,1915191,83075662,...,NaN,1915191,7567487#83075662,1,False,"[-4.3719258308, 4.6600718497999996]",1,[1.0],1,1.0
2,244,68806630,Swiss Military Hanowa,Rel√≥gio Swiss Military Hanowa06-5161.2.04.003...,Steel Swiss Made Watch with Date,249.00,EUR,NaN,2682919,60576778,...,NaN,2080188,68806630#60576778,0,True,"[3.7885432243, -4.2523846626]",0,[0.0],0,1.0
3,3811,79741016,NaN,"BenQ SW271 27\"" 4K UHD, Adobe RGB Monitor","27\"" In-Plane Switching (IPS) MonitorUSB Type-...",949,GBP,NaN,466745,45300534,...,NaN,1497038,79741016#45300534,0,False,"[3.8426625729, -4.2999582291]",0,[0.0],0,0.0
4,395,76305683,ASUS,Asus GeForce GTX 1660 SUPER Dual EVO OC 6GB - ...,Buy Asus GeForce GTX 1660 SUPER Dual EVO OC 6G...,NaN,NaN,NaN,964313,47683726,...,NaN,320546,76305683#47683726,0,True,"[3.8053600788, -4.2726025581]",0,[0.0],0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,1819,40892614,NaN,CM / COOLERMASTER MASTERLIQUID ML120R ARGB CPU...,Warranty : 2 Years with Local Distributor - Ba...,128.00,SGD,NaN,104011,33918678,...,NaN,48610,40892614#33918678,0,False,"[3.8457813263, -4.3074464798]",0,[0.0],0,NaN
396,383,79859679,NaN,EPSON cartridge T7551 black XL (WF-8xxx),CZ distribuce / 8715946539591 / C13T755140 /,2146.00,CZK,NaN,3543965,1741625,...,NaN,2334631,79859679#1741625,0,True,"[3.7946453094, -4.2569131851]",0,[0.0],0,NaN
397,945,36308180,Intel,Intel Core i7-10700KF 8-Core 5.10GHz CPU,Intel helps power the world‚Äôsfastest gamingd...,689.00,NZD,NaN,310518,81068794,...,NaN,3846144,36308180#81068794,0,True,"[3.835865736, -4.2946929932]",0,[0.0],0,NaN
398,4413,75288274,NaN,Buy Quality Replica Omega Seamaster Planet Oce...,Quality AAA Replica Omega Seamaster Planet Oce...,NaN,NaN,NaN,1476532,94565040,...,NaN,1476532,75288274#94565040,1,False,"[-4.3941354752, 4.6755304337]",1,[1.0],1,NaN
399,3742,52237675,NaN,D-LINK DGS-1210-24 Switch Smart 24 x 10/100/10...,NaN,559.158.001,PLN,NaN,793378,18108980,...,NaN,964764,52237675#18108980,0,True,"[3.6455748081, -4.1117873192]",0,[0.0],0,NaN

In [10]:
# Select all rows where the Aaron is 1
df_new = df[df['Aaron'] == 1]

In [12]:
df_new

,Unnamed: 0,id_left,brand_left,title_left,description_left,price_left,priceCurrency_left,specTableContent_left,cluster_id_left,id_right,...,specTableContent_right,cluster_id_right,pair_id,label,is_hard_negative,roberta-base_logits,roberta-base_prediction,rsupcon-base_logits,rsupcon-base_prediction,Aaron
0,1349,45334125,NaN,Pen Drive SanDisk 64GB Cruzer Glide USB 2.0,NaN,"9,86",EUR,NaN,763994,9787254,...,NaN,279041,45334125#9787254,0,True,"[3.7204918861, -4.1918787956]",0,[0.0],0,1.0
1,1056,7567487,NaN,PEN DRIVE 16GB KINGSTON USB 3.0 DTIG4/16GB,PEN DRIVE 16GB KINGSTON USB 3.0 DTIG4/16GB Dat...,Apr 84,EUR,NaN,1915191,83075662,...,NaN,1915191,7567487#83075662,1,False,"[-4.3719258308, 4.6600718497999996]",1,[1.0],1,1.0
2,244,68806630,Swiss Military Hanowa,Rel√≥gio Swiss Military Hanowa06-5161.2.04.003...,Steel Swiss Made Watch with Date,249.00,EUR,NaN,2682919,60576778,...,NaN,2080188,68806630#60576778,0,True,"[3.7885432243, -4.2523846626]",0,[0.0],0,1.0
5,3154,33138819,NaN,Baterie APC Battery kit APCRBC110,"Baterie APC Battery kit APCRBC110, Baterie, pr...",1399.70,CZK,NaN,1157842,8401,...,NaN,849634,33138819#8401,0,True,"[3.8125219345, -4.2747883797]",0,[0.0],0,1.0
6,3963,81415527,NaN,2MP 25X Network IR PTZ Camera,"1/2.8\"" progressive scan CMOSUp to 1920 √ó 108...","Incl. BTW‚Ç¨1.035,76",EUR,NaN,2694265,46810114,...,NaN,2694265,81415527#46810114,1,False,"[-4.1793274879, 4.4736194611]",1,[1.0],1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2719,90496399,NaN,G.Skill Trident Z Neo 16GB (2x8GB) 3600MHz DDR...,NaN,169.00,AUD,NaN,2024334,24200775,...,NaN,2024334,90496399#24200775,1,False,"[-4.3931255341, 4.6727685928]",1,[1.0],1,1.0
377,3248,39143149,NaN,Shimano Ultegra CS-R8000 11sp Cassette 11-28T,"Shimano, Ultegra CS-R8000, 11sp. Cassette, 11-...",164.99,CAD,NaN,895823,97999811,...,NaN,1915922,39143149#97999811,0,True,"[3.8170776367, -4.2780303955]",0,[0.0],0,1.0
378,2164,95352771,Logitech,Logitech C310 Webcam - 1 Megapixel - USB 2.0,5 Megapixel Interpolated - 1280 x 720 Video - ...,45.49,GBP,NaN,301204,12274360,...,NaN,301204,95352771#12274360,1,False,"[-4.3837895393, 4.6717839241]",1,[1.0],1,1.0
379,35,42121103,NaN,T1204171704100 Tissot Seastar 1000 Quartz,The Tissot Seastar 1000 merges style and perfo...,451.0,EUR,NaN,1167881,38366111,...,NaN,1508649,42121103#38366111,0,True,"[-1.9376914501, 1.9234960079]",1,[0.0],0,1.0
392,2822,4225266,NaN,Corsair Vengeance RGB Pro 16GB 2x8GB 288-Pin D...,DDR4 3000 (PC4 24000) Timing 15-17-17-35 CAS L...,390.00,AED,NaN,1857840,72137556,...,NaN,1857840,4225266#72137556,1,False,"[-4.3992938995, 4.6753931046]",1,[1.0],1,1.0

In [13]:
# Save df_new to csv
df_new.to_csv('data/test/curated_benchmark_aaron.csv')

In [17]:
# Load curated_benchmark_aaron.csv
df = pd.read_csv('data/test/testset.csv')
# what is the distribution of the labels?
df['label'].value_counts()

0    66
1    34
Name: label, dtype: int64